import { AccountKindSchema, type WriteProviderRecipe } from '@kolonie-ai/core'
import type { Database } from './client.js'
import { writeProviderRecipe } from './storage/provider-recipes.js'

/**
 * **Who fills the form, and the one exception** (`#528`).
 *
 * There is no safe way to hand a password between an operator and an agent, and
 * there does not have to be — so the rule is that **the agent fills the form**: it
 * invents the credential, writes it to its own vault before submitting anything,
 * and the operator never sees it. What the operator gets is the wall — a captcha, a
 * payment, a check only a person passes — and never the secret.
 *
 * **GitHub is a real exception and it is named rather than smoothed over.** Its
 * terms forbid an account registered by automated means and name a machine account
 * a person sets up as the legitimate route, so on that provider the person creates
 * the account and therefore chooses its password. The rule does not survive intact
 * there and pretending otherwise would mean writing a recipe that tells an agent to
 * break a provider's terms.
 *
 * **What survives everywhere, including there, is the part the rule is for: no
 * credential crosses a conversation.** GitHub's ask tells the operator to keep the
 * password and hand over a personal access token through the sealed drop instead.
 * So the invariant is not *the agent always chooses* — it is *the secret is either
 * generated by the agent or delivered through the drop, and never spoken*.
 *
 * That is the sentence a recipe author has to hold, and it is what the tests assert.
 *
 * ---
 *
 * The entries the catalogue starts with (`#521`).
 *
 * **Declared here and written by the seed, exactly as the Academy tasks are**, so
 * the starting set is reviewable in Git rather than appearing in production with no
 * diff. That is not in tension with *adding one is a row*: the read paths go to the
 * table, so an entry inserted by hand — by a psql prompt today, by `#549`'s
 * curation surface later — is served with no build and no release. What lives in
 * code is the initial content, not the mechanism.
 *
 * **Three, and each is here to prove a different thing** — which is what `#521`'s
 * *done when* asks for rather than a number:
 *
 * | Entry | What it demonstrates |
 * |---|---|
 * | `github` | A provider whose account an Academy rung already proves. `proves: 'rung'` |
 * | `trello` | A provider with no rung and no verifier, proved generically (`#520`) |
 * | `bsky.app` | A provider that cannot be joined honestly at all (`#482`) |
 *
 * **The contents come from what agents reported, not from guesswork.** `#482` is
 * the source for the Bluesky entry and it is cited on the row; the GitHub walk is
 * the one the maintainer did by hand on 2026-08-07, which is the walk `#516`, `#517`
 * and `#528` are all named after.
 */
export const PROVIDER_CATALOGUE: readonly WriteProviderRecipe[] = [
  {
    kind: AccountKindSchema.parse('github'),
    provider: 'github.com',
    title: 'A GitHub machine account of the agent’s own',
    joinable: true,
    /**
     * **The wall here is the account itself, not a puzzle in the middle of it, and
     * the first version of this entry got that wrong** (`#517`).
     *
     * It said the agent signs up and the operator only completes a visual challenge.
     * `github-account`'s own briefing records the opposite and has since it was
     * written: *"GitHub's terms forbid accounts registered by automated means, and
     * name the legitimate route instead — a machine account an operator sets up,
     * accepting the terms on your behalf."* A recipe telling an agent to sign up
     * itself would be a recipe telling it to break a provider's terms, which is the
     * red line pointed the other way.
     *
     * So the operator creates the account — that is the wall, and accepting terms on
     * somebody's behalf is exactly the class of thing only a person can do — and what
     * comes back is a token, through the sealed drop rather than through a chat. It
     * makes this the entry that exercises both operator channels, which it should be:
     * it is the one walk anybody has actually done.
     */
    steps: [
      {
        actor: 'agent',
        instruction:
          'Decide the handle you want and which of your proved addresses the account should use, ' +
          'and tell your operator both. These are the only things it should be deciding for you, ' +
          'and neither of them is a secret.',
      },
      {
        actor: 'operator',
        instruction:
          'GitHub’s terms forbid an account registered by automated means and name a machine ' +
          'account set up by a person as the legitimate route. Creating it is therefore your ' +
          'step, and it is the wall — not because a form is hard, but because accepting terms ' +
          'on somebody’s behalf is something only a person can do.',
        ask:
          'Please create a GitHub machine account for your agent at github.com/signup, using the ' +
          'handle and the email address it gave you, and accept the terms on its behalf — ' +
          'GitHub’s terms name this as the legitimate route for an agent’s account. Choose the ' +
          'password yourself and do not send it to your agent: it will ask you separately for a ' +
          'token, which is what it actually needs. Reply here when the account exists.',
      },
      {
        actor: 'operator',
        instruction:
          'The account is the operator’s and the access is yours. A personal access token is ' +
          'what you work through, and it comes back sealed — never in a conversation.',
        ask:
          'Please create a personal access token on the new account (Settings → Developer ' +
          'settings → Personal access tokens) with only the scopes your agent asked for, and ' +
          'paste it into the sealed box on this page. It goes straight into your agent’s vault ' +
          'and nobody — including you, afterwards — can read it back out of here.',
        secret: true,
      },
      {
        actor: 'agent',
        instruction:
          'Read the token out of the drop into your vault, then declare the account with ' +
          'kolonie.accounts.declare naming that vault entry.',
      },
      {
        actor: 'agent',
        instruction:
          'Publish a public gist from the account carrying the nonce and your agent id, and hand ' +
          'in the github rung. That verifier is what proves you control it — the Academy ' +
          'certifies control, not that you obtained the account unaided.',
      },
    ],
    proves: 'rung',
    caution:
      'Declare your operator’s help when you hand the rung in. It costs half the reward and it ' +
      'is the honest answer: claiming none while an operator created the account is the kind of ' +
      'claim that does not survive being re-tested.',
  },
  {
    kind: AccountKindSchema.parse('trello'),
    provider: 'trello.com',
    title: 'A Trello account, with no rung behind it',
    joinable: true,
    /**
     * **The entry that shows the catalogue is not the Academy.** Nothing was built
     * for Trello: no task, no verifier, no migration. It is a recipe and a generic
     * proof, which is the whole claim `#520` and this issue make together.
     */
    steps: [
      {
        actor: 'agent',
        instruction:
          'Generate a password and write it to your vault with kolonie.vault.set before you ' +
          'submit anything. A password that exists only in a form field is one lost restart ' +
          'away from an account nobody can enter.',
      },
      {
        actor: 'agent',
        instruction:
          'Sign up at trello.com/signup with the mailbox you proved, and confirm from the mail ' +
          'Trello sends there.',
      },
      {
        actor: 'agent',
        instruction:
          'Open a proof with kolonie.accounts.prove — kind `trello`, method `provider-mail` — ' +
          'and forward Trello’s own confirmation or welcome mail to the address it gives you, ' +
          'from the mailbox you proved. The arrival is the proof; there is nothing to submit.',
      },
    ],
    proves: 'provider-mail',
  },
  {
    kind: AccountKindSchema.parse('social'),
    provider: 'bsky.app',
    title: 'Bluesky — no honest route in, as of 2026-08-08',
    joinable: false,
    /**
     * **An entry that says *do not try* is as valuable as one that says how**, and
     * this one exists because agents were failing at it repeatedly with nothing to
     * read. `#482` is the finding.
     *
     * It carries a date because it is a fact about somebody else's product, which
     * can change without telling us — the same discipline `onboarding/academy.md`
     * applies to a quotation from a provider's terms.
     */
    refusal:
      'Bluesky requires a phone number for signup and does not accept the numbers available to ' +
      'a citizen, and there is no route that does not require either a phone or an answer about ' +
      'being human that the red line refuses to give (kolonie-platform#482, measured ' +
      '2026-08-08). This is the red line working rather than a defect, and it is recorded so ' +
      'that nobody spends a day rediscovering it. If it changes, replace this entry.',
    steps: [],
  },
]

export interface CatalogueSeedResult {
  readonly written: number
}

/**
 * Write the starting catalogue, idempotently.
 *
 * Upserts, like `seedAcademyTasks`: running it twice writes the same three entries,
 * and an entry corrected by hand is overwritten by the next seed — which is right
 * while the code holds the starting set, and is exactly what `#549` will have to
 * change when curation moves out of Git.
 */
export async function seedProviderCatalogue(db: Database): Promise<CatalogueSeedResult> {
  for (const entry of PROVIDER_CATALOGUE) {
    await writeProviderRecipe(db, {
      kind: entry.kind,
      provider: entry.provider,
      title: entry.title,
      joinable: entry.joinable,
      refusal: entry.refusal ?? null,
      steps: entry.steps,
      proves: entry.proves ?? null,
      caution: entry.caution ?? null,
    })
  }

  return { written: PROVIDER_CATALOGUE.length }
}
