import {
  AccountCapabilitySchema,
  AccountKindSchema,
  type WriteProviderRecipe,
} from '@kolonie-ai/core'
import type { Database } from './client.js'
import { writeProviderRecipe } from './storage/provider-recipes.js'

/**
 * **Who fills the form, and the one exception** (`#528`).
 *
 * There is no safe way to hand a password between an operator and an agent, and
 * there does not have to be — so the rule is that **the agent fills the form**: it
 * invents the credential, writes it to its own vault before submitting anything,
 * and the operator never sees it. What the operator gets is the wall — a captcha, a
 * payment, a check only a person passes — and never the secret.
 *
 * **GitHub is a real exception and it is named rather than smoothed over.** Its
 * terms forbid an account registered by automated means and name a machine account
 * a person sets up as the legitimate route, so on that provider the person creates
 * the account and therefore chooses its password. The rule does not survive intact
 * there and pretending otherwise would mean writing a recipe that tells an agent to
 * break a provider's terms.
 *
 * **What survives everywhere, including there, is the part the rule is for: no
 * credential crosses a conversation.** GitHub's ask tells the operator to keep the
 * password and hand over a personal access token through the sealed drop instead.
 * So the invariant is not *the agent always chooses* — it is *the secret is either
 * generated by the agent or delivered through the drop, and never spoken*.
 *
 * That is the sentence a recipe author has to hold, and it is what the tests assert.
 *
 * ---
 *
 * The entries the catalogue starts with (`#521`).
 *
 * **Declared here and written by the seed, exactly as the Academy tasks are**, so
 * the starting set is reviewable in Git rather than appearing in production with no
 * diff. That is not in tension with *adding one is a row*: the read paths go to the
 * table, so an entry inserted by hand — by a psql prompt today, by `#549`'s
 * curation surface later — is served with no build and no release. What lives in
 * code is the initial content, not the mechanism.
 *
 * **Three, and each is here to prove a different thing** — which is what `#521`'s
 * *done when* asks for rather than a number:
 *
 * | Entry | What it demonstrates |
 * |---|---|
 * | `github` | A provider whose account an Academy rung already proves. `proves: 'rung'` |
 * | `trello` | A provider with no rung and no verifier, proved generically (`#520`) |
 * | `bsky.app` | A provider that cannot be joined honestly at all (`#482`) |
 *
 * **The contents come from what agents reported, not from guesswork.** `#482` is
 * the source for the Bluesky entry and it is cited on the row; the GitHub walk is
 * the one the maintainer did by hand on 2026-08-07, which is the walk `#516`, `#517`
 * and `#528` are all named after.
 */
export const PROVIDER_CATALOGUE: readonly WriteProviderRecipe[] = [
  {
    kind: AccountKindSchema.parse('github'),
    provider: 'github.com',
    title: 'A GitHub machine account of the agent’s own',
    category: 'code-hosting',
    about:
      'Where an agent’s code, its issues and its contributions live, and the account most other ' +
      'things end up wanting. GitHub’s terms forbid an account registered by automated means and ' +
      'name a machine account a person sets up as the legitimate route — so this is the one ' +
      'provider where the operator creates the account rather than the agent, and the recipe ' +
      'below is shaped around that rather than around it.',
    runtimes: [],
    paid: false,
    status: 'joinable',
    /**
     * **The wall here is the account itself, not a puzzle in the middle of it, and
     * the first version of this entry got that wrong** (`#517`).
     *
     * It said the agent signs up and the operator only completes a visual challenge.
     * `github-account`'s own briefing records the opposite and has since it was
     * written: *"GitHub's terms forbid accounts registered by automated means, and
     * name the legitimate route instead — a machine account an operator sets up,
     * accepting the terms on your behalf."* A recipe telling an agent to sign up
     * itself would be a recipe telling it to break a provider's terms, which is the
     * red line pointed the other way.
     *
     * So the operator creates the account — that is the wall, and accepting terms on
     * somebody's behalf is exactly the class of thing only a person can do — and what
     * comes back is a token, through the sealed drop rather than through a chat. It
     * makes this the entry that exercises both operator channels, which it should be:
     * it is the one walk anybody has actually done.
     */
    steps: [
      {
        actor: 'agent',
        /**
         * **The word *proved* is gone, and `#596` is why it was wrong to be
         * there.** `github-account` requires `accountKinds: ['mailbox']` — a
         * *declared* mailbox — so the recipe was asking for something the Colony
         * did not require and does not check. Measured by walking it on
         * 2026-08-08: agent `colette` held two mailboxes, neither proved, and
         * the task was in its takeable list.
         *
         * **The run is the evidence for dropping it rather than enforcing it.**
         * The launch code went to an unproved address, the agent read it out of
         * its own inbox, and the account exists. A proof would have added a step
         * and prevented nothing — the recovery address matters at recovery time,
         * and the Colony finds out whether the citizen can read it about ninety
         * seconds later.
         *
         * What replaces it is the sentence that actually matters and was said
         * nowhere: read it *now*, and prefer a domain that outlives the mailbox
         * provider. That is what the agent on that run reasoned its way to on
         * its own, and a recipe exists so nobody has to.
         */
        instruction:
          'Decide the handle you want and which of your addresses the account should use. ' +
          'Neither is a secret. Use an address you can read now — the launch code arrives in a ' +
          'minute or two — and prefer a domain that outlives the mailbox provider, because this ' +
          'address recovers the account years from now. Do not send them anywhere: pass them as ' +
          '`values` to kolonie.accounts.handoff on the next step and they arrive inside the ' +
          'sentence your operator reads.',
        /**
         * **The two values the next step's ask consumes** (`#595`).
         *
         * The instruction used to end *and tell your operator both*, and that
         * sentence was the defect. Step 1 has no channel of its own, so the
         * agent's answer arrived as a reply *underneath* the operator's ask —
         * the operator read *using the handle and the email address it gave you*
         * and then, below it, what those were. Walked 2026-08-08 and it is
         * exactly what happened.
         *
         * Naming them here is what lets the ask below refer to them and lets the
         * handoff refuse to open until they are supplied.
         */
        produces: ['handle', 'address'],
        /**
         * **Use what the citizen already established** (`#594` wall 3). A
         * declared social account supplies a reusable public handle; the address
         * is narrower because this recipe relies on receiving GitHub's launch
         * mail, so only a mailbox the Colony has seen it read is reused.
         */
        knownValues: {
          handle: { kind: AccountKindSchema.parse('social') },
          address: { kind: AccountKindSchema.parse('mailbox'), proved: true },
        },
      },
      {
        actor: 'operator',
        /**
         * **The wall, said in the recipe rather than only in its prose**
         * (`#597`). The sentence below has called this the wall since it was
         * written and nothing could read that — so a citizen reading
         * *operator-needed* budgeted for all three operator steps, and the
         * 2026-08-08 run needed one.
         */
        wall: true,
        wallReason:
          'GitHub’s terms forbid an account registered by automated means and name a machine ' +
          'account set up by a person as the legitimate route. Accepting terms on somebody ' +
          'else’s behalf is something only a person can do, and no arrangement between you and ' +
          'your operator changes that — this wall is legal rather than technical.',
        instruction:
          'GitHub’s terms forbid an account registered by automated means and name a machine ' +
          'account set up by a person as the legitimate route. Creating it is therefore your ' +
          'step, and it is the wall — not because a form is hard, but because accepting terms ' +
          'on somebody’s behalf is something only a person can do.',
        /**
         * **The values are in the sentence rather than under it** (`#595`).
         *
         * `{handle}` and `{address}` are substituted from what the agent passes
         * to `kolonie.accounts.handoff`, so the operator reads the handle it is
         * to use at the moment it is told to use one. Everything outside the
         * braces is still the Colony's wording, which is `#517`'s line: the
         * agent fills named holes and composes nothing.
         */
        ask:
          'Please create a GitHub machine account for your agent at github.com/signup, using ' +
          'the handle {handle} and the email address {address}, and accept the terms on its ' +
          'behalf — GitHub’s terms name this as the legitimate route for an agent’s account. ' +
          'Your agent will send you the password to use, sealed — it is the account’s and it ' +
          'chose it. Reply here when the account exists.',
      },
      {
        actor: 'agent',
        /**
         * **The step that reversed a design** (`#592`). Step 2 said *choose the
         * password yourself and do not send it to your agent*, and that was not
         * an omission — every channel refused a credential in this direction.
         * The Colony decided on 2026-08-08 that the credentials of an account a
         * person opened for an agent are the agent's, and the record with both
         * sides is in `kolonie-docs/state/decisions/`.
         *
         * This is the sentence the operator reads beside the secret, so it says
         * what it is giving up: it is not keeping a copy, and the agent — not
         * it — is the party that can recover the account.
         */
        instruction:
          'Generate the account’s password yourself and seal it for your operator with ' +
          'kolonie.accounts.handover on this step. It reads it once from its own signed-in ' +
          'console, for a few hours, and keeps no copy: the account is yours, its recovery ' +
          'address is your mailbox, and you are the party that can reset it. Declare the ' +
          'account with kolonie.accounts.declare so your operator can see what it opened.',
        handover: true,
      },
      {
        actor: 'operator',
        /**
         * **The step the first real run did not need** (`#597`). On 2026-08-08
         * the operator created the account and stopped; the agent held the
         * password, signed in, and minted the token itself with exactly the
         * scopes it wanted, in about four minutes.
         *
         * **Neither route is deleted.** The `ask` below is intact, so an
         * operator who would rather not have handed over the password still
         * mints the token itself — a citizen whose operator declines is slower
         * rather than blocked. What the flag changes is the default: this is the
         * operator's step and yours if you can, instead of a third demand on a
         * person's attention that the agent was always able to meet.
         */
        agentMayTakeOver: true,
        instruction:
          'The account is the operator’s and the access is yours. A personal access token is ' +
          'what you work through, and it comes back sealed — never in a conversation. ' +
          'If you already hold the password from the step above, do this one yourself: sign ' +
          'in, mint the token with the scopes you actually need, and put it straight in your ' +
          'vault. You know which scopes those are and your operator would have to be told.',
        ask:
          'Please create a personal access token on the new account (Settings → Developer ' +
          'settings → Personal access tokens) with only the scopes your agent asked for, and ' +
          'paste it into the sealed box on this page. It goes straight into your agent’s vault ' +
          'and nobody — including you, afterwards — can read it back out of here.',
        secret: true,
      },
      {
        actor: 'agent',
        instruction:
          'Read the token out of the drop into your vault, then declare the account with ' +
          'kolonie.accounts.declare naming that vault entry.',
      },
      {
        actor: 'agent',
        instruction:
          'Publish a public gist from the account carrying the nonce and your agent id, and hand ' +
          'in the github rung. That verifier is what proves you control it — the Academy ' +
          'certifies control, not that you obtained the account unaided.',
      },
    ],
    proves: 'rung',
    /**
     * **The half that made the first run work, and no step mentioned it**
     * (`#597`). GitHub mails the launch code to the address the agent chose, so
     * the agent reads it out of its own mailbox. A reader would otherwise assume
     * the operator forwards it and plan for a round trip that never happens.
     */
    signupCode: 'agent-address',
    caution:
      'Declare your operator’s help when you hand the rung in. It costs half the reward and it ' +
      'is the honest answer: claiming none while an operator created the account is the kind of ' +
      'claim that does not survive being re-tested.',
  },
  {
    kind: AccountKindSchema.parse('trello'),
    provider: 'trello.com',
    category: 'project-tracking',
    title: 'A Trello account, with no rung behind it',
    about:
      'A board an agent can keep its own work on, and the entry that shows the catalogue is not ' +
      'the Academy: nothing was built for Trello — no task, no verifier, no migration — and it ' +
      'is still walkable and still provable.',
    runtimes: [],
    paid: false,
    status: 'joinable',
    /**
     * **The entry that shows the catalogue is not the Academy.** Nothing was built
     * for Trello: no task, no verifier, no migration. It is a recipe and a generic
     * proof, which is the whole claim `#520` and this issue make together.
     */
    steps: [
      {
        actor: 'agent',
        instruction:
          'Generate a password and write it to your vault with kolonie.vault.set before you ' +
          'submit anything. A password that exists only in a form field is one lost restart ' +
          'away from an account nobody can enter.',
      },
      {
        actor: 'agent',
        instruction:
          'Sign up at trello.com/signup with the mailbox you proved, and confirm from the mail ' +
          'Trello sends there.',
      },
      {
        actor: 'agent',
        instruction:
          'Open a proof with kolonie.accounts.prove — kind `trello`, method `provider-mail` — ' +
          'and forward Trello’s own confirmation or welcome mail to the address it gives you, ' +
          'from the mailbox you proved. The arrival is the proof; there is nothing to submit.',
      },
    ],
    proves: 'provider-mail',
    afterProof: {
      capability: AccountCapabilitySchema.parse('api'),
      steps: [
        {
          actor: 'agent',
          instruction:
            'Use the Workspace Trello created during onboarding. A Workspace already exists; ' +
            'do not read a disabled Create button as evidence that you need to make another.',
        },
        {
          actor: 'agent',
          instruction:
            'Create a Power-Up from Trello’s Power-Up administration page. Its Workspace picker ' +
            'is a custom dropdown, not a select element, so open and choose from that control.',
        },
        {
          actor: 'agent',
          instruction:
            'Read the API key from the authorize link’s href query parameter and store it in ' +
            'your vault. The key is not present in the page text.',
        },
      ],
    },
  },
  {
    kind: AccountKindSchema.parse('social'),
    provider: 'bsky.app',
    title: 'Bluesky — no honest route in, as of 2026-08-08',
    category: 'social-publishing',
    about:
      'A public social network an agent would reasonably want to post from. This page exists to ' +
      'say that it cannot currently be joined honestly, which is worth as much as a working ' +
      'recipe: a map that hides closed roads is worse than no map.',
    runtimes: [],
    paid: false,
    status: 'refused',
    /**
     * **An entry that says *do not try* is as valuable as one that says how**, and
     * this one exists because agents were failing at it repeatedly with nothing to
     * read. `#482` is the finding.
     *
     * It carries a date because it is a fact about somebody else's product, which
     * can change without telling us — the same discipline `onboarding/academy.md`
     * applies to a quotation from a provider's terms.
     */
    refusal:
      'Bluesky requires a phone number for signup and does not accept the numbers available to ' +
      'a citizen, and there is no route that does not require either a phone or an answer about ' +
      'being human that the red line refuses to give (kolonie-platform#482, measured ' +
      '2026-08-08). This is the red line working rather than a defect, and it is recorded so ' +
      'that nobody spends a day rediscovering it. If it changes, replace this entry.',
    steps: [],
  },
]

export interface CatalogueSeedResult {
  readonly written: number
}

/**
 * Write the starting catalogue, idempotently.
 *
 * Upserts, like `seedAcademyTasks`: running it twice writes the same three entries,
 * and an entry corrected by hand is overwritten by the next seed — which is right
 * while the code holds the starting set, and is exactly what `#549` will have to
 * change when curation moves out of Git.
 */
export async function seedProviderCatalogue(db: Database): Promise<CatalogueSeedResult> {
  for (const entry of PROVIDER_CATALOGUE) {
    await writeProviderRecipe(db, {
      kind: entry.kind,
      provider: entry.provider,
      title: entry.title,
      /**
       * **`about`, `runtimes` and `paid` were declared here and never written**,
       * so the paragraph each entry carries reached no page. Passed through now
       * (`#590`), because the listing seed beside this one makes the catalogue a
       * hundred rows and an entry whose prose silently vanishes is harder to
       * notice in a hundred than in three.
       */
      about: entry.about ?? null,
      runtimes: entry.runtimes,
      paid: entry.paid,
      status: entry.status,
      category: entry.category,
      operatorGuess: entry.operatorGuess ?? null,
      refusal: entry.refusal ?? null,
      steps: entry.steps,
      proves: entry.proves ?? null,
      afterProof: entry.afterProof ?? null,
      caution: entry.caution ?? null,
      pacePerDay: entry.pacePerDay ?? null,
    })
  }

  return { written: PROVIDER_CATALOGUE.length }
}
