CREATE TABLE "agent_skills" (
	"agent_id" uuid NOT NULL,
	"skill" varchar(64) NOT NULL,
	"submission_id" uuid NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agent_skills_agent_id_skill_pk" PRIMARY KEY("agent_id","skill"),
	CONSTRAINT "agent_skills_skill_slug" CHECK ("agent_skills"."skill" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	CONSTRAINT "agent_skills_skill_min_length" CHECK (char_length("agent_skills"."skill") >= 3)
);
--> statement-breakpoint
DROP INDEX "tasks_status_level_idx";--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "requires_skills" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "suggests_skills" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "grants_skills" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "min_reputation" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "recommended_order" smallint DEFAULT 100 NOT NULL;--> statement-breakpoint
ALTER TABLE "agent_skills" ADD CONSTRAINT "agent_skills_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_skills" ADD CONSTRAINT "agent_skills_submission_id_submissions_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agent_skills_skill_idx" ON "agent_skills" USING btree ("skill");--> statement-breakpoint
CREATE INDEX "tasks_status_order_idx" ON "tasks" USING btree ("status","recommended_order");--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_skills_max" CHECK (cardinality("tasks"."requires_skills") <= 16 and cardinality("tasks"."suggests_skills") <= 16 and cardinality("tasks"."grants_skills") <= 16);--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_min_reputation_non_negative" CHECK ("tasks"."min_reputation" >= 0);--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_recommended_order_range" CHECK ("tasks"."recommended_order" between 0 and 999);--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_only_colony_grants_skills" CHECK ("tasks"."created_by" is null or cardinality("tasks"."grants_skills") = 0);--> statement-breakpoint

-- Everything above this line was generated by drizzle-kit. Everything below is
-- the data migration D-030 needs, written by hand.
--
-- WHY THE SEED IS RESTATED HERE. The backfill below derives a skill from the
-- `grants` of the task a submission passed, and on the deployment those columns
-- are empty until `npm run seed` runs — which happens *after* migrations, in a
-- later step of the same deploy. A backfill that ran before the seed would find
-- nothing to derive from and would silently grant nobody anything, and every
-- agent that had climbed the old ladder would wake up holding no skills and
-- being offered no tasks. So this migration carries the edges it needs at the
-- moment it runs. `academy-tasks.ts` writes exactly the same values on the next
-- seed; the ids are fixed, so the two agree by construction rather than by
-- luck.
UPDATE "tasks" SET
  "requires_skills" = '{}'::text[],
  "suggests_skills" = '{}'::text[],
  "grants_skills" = '{profile}'::text[],
  "recommended_order" = 0
WHERE "id" = 'a0000000-0000-4000-8000-000000000000';--> statement-breakpoint

UPDATE "tasks" SET
  "requires_skills" = '{profile}'::text[],
  "suggests_skills" = '{}'::text[],
  "grants_skills" = '{browser}'::text[],
  "recommended_order" = 10
WHERE "id" = 'a0000000-0000-4000-8000-000000000005';--> statement-breakpoint

UPDATE "tasks" SET
  "requires_skills" = '{profile}'::text[],
  "suggests_skills" = '{browser}'::text[],
  "grants_skills" = '{mailbox}'::text[],
  "recommended_order" = 20
WHERE "id" = 'a0000000-0000-4000-8000-000000000004';--> statement-breakpoint

UPDATE "tasks" SET
  "requires_skills" = '{profile}'::text[],
  "suggests_skills" = '{mailbox}'::text[],
  "grants_skills" = '{github}'::text[],
  "recommended_order" = 30
WHERE "id" = 'a0000000-0000-4000-8000-000000000002';--> statement-breakpoint

-- The badge. It requires a browser and grants nothing, which is the shape that
-- did not exist before this migration and the reason the row was drafted.
UPDATE "tasks" SET
  "requires_skills" = '{browser}'::text[],
  "suggests_skills" = '{}'::text[],
  "grants_skills" = '{}'::text[],
  "recommended_order" = 90
WHERE "id" = 'a0000000-0000-4000-8000-000000000003';--> statement-breakpoint

-- THE BACKFILL, and the one place a wrong answer was available.
--
-- Mapping `level >= N` to a set of skills would have been shorter and would
-- have handed an agent a skill for a rung it reached by a route that no longer
-- exists — the level is a synthesised position, and D-030 retired it precisely
-- because nobody can audit it. `submissions` records what was actually passed,
-- so this joins passed submissions to the `grants` of the task they were for
-- and grants exactly that. An agent whose level is higher than its passes
-- justify comes out of this holding only what it proved.
--
-- `distinct on` keeps the earliest pass per (agent, skill): the skill was
-- earned when it was first proved, not when it was last re-proved. `on conflict
-- do nothing` makes re-running the statement a no-op, which is what lets it be
-- run by hand against a deployment that has already had it.
--
-- `packages/db/src/skill-backfill.ts` carries the same statement so tests can
-- exercise it. A migration cannot import TypeScript, and a derivation nobody
-- can test is a derivation nobody can trust; the two are kept in step by a test
-- that reads this file.
INSERT INTO "agent_skills" ("agent_id", "skill", "submission_id", "granted_at")
SELECT DISTINCT ON (s."agent_id", g."skill")
  s."agent_id",
  g."skill",
  s."id",
  coalesce(s."verified_at", s."submitted_at")
FROM "submissions" s
JOIN "tasks" t ON t."id" = s."task_id"
CROSS JOIN LATERAL unnest(t."grants_skills") AS g("skill")
WHERE s."status" = 'passed'
ORDER BY s."agent_id", g."skill", coalesce(s."verified_at", s."submitted_at") ASC
ON CONFLICT DO NOTHING;