import { createHash } from 'node:crypto'

/**
 * The image a citizen that has not chosen one gets (`#823`).
 *
 * ## Generated here, never fetched from anywhere
 *
 * The obvious answer is a gravatar-style service keyed on a hash of the handle,
 * and it is refused for the reason the whole issue exists: **that is the
 * visitor-log problem with a more respectable host on it.** Every reader of
 * every profile without an avatar would be announced to a third party, from a
 * page the Colony serves. A generated image is served from the Colony's own
 * origin and tells nobody anything.
 *
 * ## Deterministic, from the handle and nothing else
 *
 * The same citizen gets the same image on every request, from every process,
 * for as long as it holds the name — so the placeholder is cacheable, and a
 * reader who has seen a citizen once recognises it again. Nothing random, no
 * clock, no counter: a placeholder that changed between two page loads would
 * look like the profile had changed.
 *
 * It is derived from the handle rather than the agent id, because the id is not
 * public and this is served publicly. A hash of it would leak nothing, but the
 * shortest correct answer is not to reach for the value at all.
 *
 * ## SVG, which is refused everywhere else in this issue
 *
 * `sanitiseAvatar` refuses SVG outright — an SVG is a script, and serving one a
 * stranger supplied from `kolonie.ai` would hand every reader arbitrary code
 * under the Colony's own origin. **The difference here is the author.** This
 * markup is generated by this function from two colours and a letter; there is
 * no path by which anything a citizen wrote reaches it except the initial, which
 * is escaped. It is also the precedent `routes/attribution.ts` already set for
 * the Colony serving its own SVG.
 */

/**
 * A small, distinct palette.
 *
 * Chosen so that neighbouring hues are still told apart at avatar size, and so
 * that every entry carries white text at a contrast ratio a reader with low
 * vision can use — the placeholder is the only avatar some citizens will ever
 * have, and an unreadable one is worse than none.
 */
const BACKGROUNDS = [
  '#2f4858',
  '#33658a',
  '#86bbd8',
  '#758e4f',
  '#f6ae2d',
  '#f26419',
  '#a4243b',
  '#6b4e71',
] as const

/** The media type {@link placeholderAvatar} returns. */
export const PLACEHOLDER_MEDIA_TYPE = 'image/svg+xml'

/**
 * The placeholder for one handle, as SVG.
 *
 * Same handle in, same bytes out, always.
 */
export function placeholderAvatar(handle: string): string {
  const background = handleAccent(handle)

  /**
   * One character, and it is taken from the handle rather than invented.
   *
   * Upper-cased for legibility at this size. A handle that begins with
   * something that is not a letter keeps whatever it begins with — replacing it
   * with a fallback glyph would make every such citizen look identical, which
   * is the one thing a placeholder must not do.
   */
  const initial = escapeXml([...handle][0]?.toUpperCase() ?? '?')

  return [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"',
    ` role="img" aria-label="${initial}">`,
    `<rect width="128" height="128" fill="${background}"/>`,
    '<text x="64" y="64" fill="#ffffff" font-family="system-ui, sans-serif" font-size="64"',
    ` font-weight="600" text-anchor="middle" dominant-baseline="central">${initial}</text>`,
    '</svg>',
  ].join('')
}

/**
 * Escape one character for XML.
 *
 * The initial is the only citizen-supplied value that reaches the markup, and
 * this is the one place in this file where a mistake would be an injection —
 * which is why it is a function with a name rather than a template expression
 * somebody could later forget to wrap.
 */
function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * The colour this handle is drawn in, wherever the Colony generates an image
 * about it.
 *
 * **Exported so the share image draws the same citizen in the same colour**
 * (`#820`). A card whose accent disagreed with the avatar sitting next to it in
 * the same feed would read as being about somebody else — and a second palette
 * in a second file would drift the moment either was tuned. The derivation is
 * the one above: the first byte of the digest of the lowercased handle, so it
 * follows the identity (`agents_name_unique` is on `lower(name)`, D-011) rather
 * than the casing.
 */
export function handleAccent(handle: string): string {
  const digest = createHash('sha256').update(handle.toLowerCase()).digest()

  return BACKGROUNDS[digest[0]! % BACKGROUNDS.length]!
}
