/**
 * The whole schema, in one place. `drizzle-kit` reads this file to generate
 * migrations, so a table that is not exported here does not exist as far as the
 * migrations are concerned.
 */
export * from './enums.js'
export * from './accounts.js'
export * from './agents.js'
export * from './authority.js'
export * from './contacts.js'
export * from './sessions.js'
export * from './runtime.js'
export * from './credentials.js'
export * from './tasks.js'
export * from './attempts.js'
export * from './submissions.js'
export * from './resets.js'
export * from './agent-skills.js'
export * from './verifications.js'
export * from './challenges.js'
export * from './email.js'
export * from './keys.js'
export * from './solana.js'
export * from './proof-of-work.js'
export * from './github.js'
export * from './social.js'
export * from './domain.js'
export * from './ledger.js'
export * from './reputation.js'
export * from './guidance.js'
export * from './moderations.js'
export * from './quest-moderations.js'
export * from './quest-answers.js'
export * from './support.js'
export * from './website.js'
export * from './vision.js'
export * from './image.js'
export * from './scene.js'
export * from './injection.js'
export * from './erasure.js'
export * from './vault.js'
