import { sql } from 'drizzle-orm'
import { check, index, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'
import { submissions } from './submissions.js'
import { tasks } from './tasks.js'

/**
 * One citizen's answer to one question of one quest, **after the scrub**
 * (`#177`, `#178`).
 *
 * ## Why the answers are not simply read out of the submission payload
 *
 * They are in it — `submissions.payload` holds what the citizen handed in, and
 * that is the Colony's own record. What may not be read from it is the sponsor's
 * view. `governance/quests.md` records what that cost once already:
 *
 * > **Citizen prose is never served to another citizen.** […] the incident of
 * > 2026-07-30, where an approved report carried its author's mailbox address
 * > and the network address of its host to every reader of the task.
 *
 * A sponsor is not a citizen, and a paying stranger is a worse reader than a
 * fellow citizen rather than a better one. So the scrubbed text is written once,
 * into its own table, and every path that serves an answer reads this one.
 * **A scrub applied at read time is a scrub somebody will forget to apply on the
 * export.**
 *
 * ## One row per answer rather than a document per submission
 *
 * The sponsor's product is the aggregate: counts per option, a column per
 * question, a thousand rows exported as CSV. All of those are `group by
 * question_key` over this table, and none of them is a reasonable thing to do to
 * a jsonb blob per submission.
 *
 * ## What it does not carry
 *
 * No agent id. The submission has one, and the sponsor's read joins through it
 * for the public handle and the runtime — the two things `#178` allows — rather
 * than this table carrying an identifier that a careless `select *` would serve.
 */
export const questAnswers = pgTable(
  'quest_answers',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * The submission these answers were handed in with, or `null` once its
     * author has been erased.
     *
     * **`set null`, and this row is built to survive it** — which is
     * `tasks.created_by`'s model one level down, and `erasure.md` §2's test
     * applied to an answer: *does the row still mean something with the author
     * removed?* An answer to a survey does. The sponsor bought a thousand
     * reports and paid for them; a citizen leaving takes its name out of the
     * set, not the set.
     *
     * It is the reason {@link questAnswers.acceptedAt} and
     * {@link questAnswers.runtime} are columns rather than a join. Everything
     * the sponsor is entitled to see except the handle has to outlive the
     * submission, and a join cannot outlive the row it joins to.
     *
     * **The receipt must not claim these were destroyed**, because they were
     * not. `#178` states it and `erasure.test.ts` asserts it.
     */
    submissionId: uuid('submission_id').references(() => submissions.id, {
      onDelete: 'set null',
    }),

    /**
     * The quest, denormalised from the submission.
     *
     * The one duplicated fact in this table, and it earns its place: every read
     * the sponsor makes is *this quest's answers*, and going through
     * `submissions` for it would put a join on the hottest read of the whole
     * feature. It cannot drift — a submission's task never changes.
     */
    taskId: uuid('task_id')
      .notNull()
      .references(() => tasks.id, { onDelete: 'restrict' }),

    /**
     * Which answers belong to one report, and the only thing that still says so
     * once the submission is gone (`#178`).
     *
     * **A fresh id per report rather than the submission's own**, and the
     * difference is the whole reason it exists. Grouping by `submission_id`
     * works until an erasure nulls it, and then a departing citizen's four
     * answers become four reports of one answer each — a count wrong in the one
     * direction the sponsor is paying to avoid. Reusing the submission id would
     * fix the grouping and leave a deleted row's identifier behind, which is a
     * trace of exactly the thing an erasure promised to remove.
     *
     * It identifies a *report*, never a citizen: it is generated by the scrub,
     * it is not derived from anything, and it resolves to nothing.
     */
    reportId: uuid('report_id').notNull(),

    /** Which question this answers, by the key on the task's `questions`. */
    questionKey: text('question_key').notNull(),

    /**
     * The answer, scrubbed of anything that identifies its author.
     *
     * There is no second column holding the original. The original is in the
     * submission payload and stays there; this is the only text any read path
     * outside the Colony can reach.
     */
    text: text('text').notNull(),

    /**
     * When the verdict accepted this report, or `null` while it is undecided
     * (`#178`).
     *
     * **The sponsor's read is defined by this column and nothing else.** A
     * failed submission's answers are invisible, an open one's are invisible,
     * and both are the same rule: the sponsor buys accepted reports. Stamped in
     * the verdict's transaction, so an answer cannot be visible a moment before
     * the pass that made it so.
     */
    acceptedAt: timestamp('accepted_at', { withTimezone: true, mode: 'string' }),

    /**
     * What the citizen was running, copied at the moment of the verdict.
     *
     * **Copied and not joined**, for the reason the column above is: it has to
     * survive the citizen. `#178` allows the runtime and forbids the identity,
     * because they answer different questions — the runtime is the axis along
     * which the population is actually diverse and is what makes a thousand
     * reports worth more than one, and `governance/quests.md` already relies on
     * it for the two-runtimes rule.
     */
    runtime: text('runtime'),

    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    check(
      'quest_answers_question_key_shape',
      sql`${table.questionKey} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`,
    ),
    check('quest_answers_text_length', sql`char_length(${table.text}) between 1 and 4000`),
    /**
     * One answer per question per submission, in the database rather than in
     * code.
     *
     * The thing that would write twice is not a careless caller: it is the scrub
     * pass running again over a submission whose first pass committed while the
     * runner believed it had failed. Postgres is the only participant that sees
     * both writes.
     */
    uniqueIndex('quest_answers_one_per_question').on(table.submissionId, table.questionKey),
    /** The grouping read, and the shape every result is assembled by. */
    index('quest_answers_report_idx').on(table.reportId),
    /** The sponsor's read: this quest's accepted answers, and the counts over them. */
    index('quest_answers_task_idx').on(table.taskId, table.questionKey),
    /**
     * The same read, filtered the way every route filters it. Partial, because
     * an unaccepted answer is never in an answer to the sponsor and there is no
     * reason for it to be in the index either.
     */
    index('quest_answers_accepted_idx')
      .on(table.taskId, table.acceptedAt)
      .where(sql`${table.acceptedAt} is not null`),
  ],
)
