/**
 * What the catalogue *is*, with every word of prose taken out (`#1227`).
 *
 * ## The question this answers
 *
 * `#1115`, `#1117` and `#1229`–`#1231` rewrite published descriptions in bulk.
 * A reviewer reading one of those diffs has a single question — *did anything
 * but the prose move?* — and no way to answer it: the interesting change is
 * three schema lines buried in eight hundred lines of rewritten sentences, and
 * a rewrite that quietly drops an enum value or loosens a `maxLength` reads
 * exactly like one that did not.
 *
 * So the structure is committed as a snapshot with all `description` strings
 * stripped, and this compares the served catalogue against it. **Equal means
 * the change was prose**, and the reviewer can stop looking. Unequal means the
 * snapshot moved in the same commit, and the structural change is then visible
 * on its own, in a file of its own, a few lines long.
 *
 * ## Why it names what changed rather than only that something did
 *
 * The catalogue floor could fail with one number because one number was the
 * whole of its subject (it is gone — `#1649`, D-137). This one fails on a tree,
 * and a failure reading *the structure differs* would send its reader to a
 * two-thousand-line JSON diff — the very thing the snapshot exists to spare
 * them. The verdict carries paths:
 * `kolonie.quests.write » properties.slots.maximum: 10000 → 1000`.
 *
 * ## What this deliberately does not do
 *
 * **Rewrite the snapshot when it disagrees.** A ratchet may lower itself by
 * itself, because there the new number is the finding. Here the finding is the
 * diff, and a check that silently updates the file it compares against is a
 * check nobody reads the output of. The snapshot is regenerated by a command the
 * failure names, deliberately as a separate act.
 */

import { createHash } from 'node:crypto'
import type { PublishedTool } from './catalogue-size.js'

/** One tool, as structure: its name and its schema with the prose taken out. */
export interface ToolStructure {
  readonly name: string
  readonly schema: unknown
}

/** The catalogue as structure, tools in name order so a diff is stable. */
export interface CatalogueStructure {
  readonly tools: readonly ToolStructure[]
}

/** The committed snapshot: a structure, plus the provenance AGENTS.md §7 asks of a measurement. */
export interface CatalogueStructureSnapshot extends CatalogueStructure {
  readonly measuredAt: string
  readonly command: string
}

/**
 * The same value with every `description` *annotation* gone and every object key sorted.
 *
 * **A property called `description` is structure, not prose.** `kolonie.quests.write`
 * has one, and a strip that went by key name alone would drop the field itself —
 * the snapshot would then be blind to exactly the change it exists to catch. So
 * the walk knows where it is: under `properties`, `$defs` and `definitions` the
 * keys are field names and every one of them is kept; anywhere else `description`
 * is the JSON Schema annotation and goes.
 *
 * Sorting is what makes the snapshot a *diff*: property order in a schema is an
 * accident of how the Zod object was written, so without it a reordered field
 * declaration would read as a structural change and the check would cry wolf on
 * the first refactor.
 */
const NAME_MAPS: readonly string[] = ['properties', '$defs', 'definitions']

const withoutProse = (value: unknown, keysAreNames = false): unknown => {
  if (Array.isArray(value)) return value.map((nested) => withoutProse(nested))
  if (value === null || typeof value !== 'object') return value

  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([key]) => keysAreNames || key !== 'description')
    .map(
      ([key, nested]) =>
        [key, withoutProse(nested, !keysAreNames && NAME_MAPS.includes(key))] as const,
    )
    .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))

  return Object.fromEntries(entries)
}

/** The published catalogue as structure. Takes what the client received, never a list this module builds. */
export const structureOf = (tools: readonly PublishedTool[]): CatalogueStructure => ({
  tools: [...tools]
    .map((tool) => ({ name: tool.name, schema: withoutProse(tool.inputSchema) }))
    .sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0)),
})

/**
 * The catalogue's shape as one short string (`#1392`).
 *
 * **What a client compares to find out its binding is old.** An MCP client binds
 * every tool's schema at connect and the Colony has no way to push at it —
 * `#386` deliberately does not advertise `notifications/tools/list_changed`,
 * because the transport builds a fresh server per request and there is no open
 * connection belonging to any citizen at the instant a release changes the
 * catalogue. So the question is not *how do we push*, it is *what can a citizen
 * pull that tells it its copy is stale*, and this is the cheapest honest answer.
 *
 * **Computed over the same structure the snapshot commits**, which is what makes
 * it mean the right thing: `description` is stripped, so a prose rewrite leaves
 * the fingerprint alone and a citizen is not sent to reconnect for nothing.
 * Adding a tool, removing one, or adding a required property to one it already
 * holds all move it — and the last of those is `#1360`/`#1380`, the change that
 * exposed this having no signal at all.
 *
 * **Twelve hex characters.** It is compared for equality and never inverted, so
 * what it costs on every waking matters more than collision resistance nobody
 * needs: 48 bits against a catalogue that changes a few times a week.
 */
export const fingerprintOf = (structure: CatalogueStructure): string =>
  createHash('sha256').update(JSON.stringify(structure.tools)).digest('hex').slice(0, 12)

/** Every leaf of one tool's schema, as `path` → the value written out. */
const leaves = (value: unknown, path: string, into: Map<string, string>): void => {
  if (value !== null && typeof value === 'object') {
    const entries = Array.isArray(value)
      ? value.map((nested, index) => [String(index), nested] as const)
      : Object.entries(value as Record<string, unknown>)

    if (entries.length === 0) {
      into.set(path, Array.isArray(value) ? '[]' : '{}')
      return
    }

    for (const [key, nested] of entries) leaves(nested, path === '' ? key : `${path}.${key}`, into)
    return
  }

  into.set(path, JSON.stringify(value) ?? 'undefined')
}

/** Every leaf of the whole catalogue, keyed by `tool » path`. */
const flatten = (structure: CatalogueStructure): Map<string, string> => {
  const flat = new Map<string, string>()

  for (const tool of structure.tools) {
    const own = new Map<string, string>()
    leaves(tool.schema, '', own)
    for (const [path, leaf] of own)
      flat.set(`${tool.name} » ${path === '' ? 'inputSchema' : path}`, leaf)
  }

  return flat
}

/** How many differences a verdict spells out before it stops. Enough to act on, short of a wall of text. */
export const DIFFERENCES_NAMED = 40

/** Whether the served catalogue still has the shape the snapshot recorded, and where it does not. */
export interface StructureVerdict {
  readonly unchanged: boolean
  /** Every difference, `-` gone, `+` added, `~` changed. Complete, however long. */
  readonly differences: readonly string[]
  /** What to put in front of a reader: the first {@link DIFFERENCES_NAMED}, and the way to regenerate. */
  readonly message: string
}

/** The command that rewrites the snapshot. Named in every failure, because a check that hides its own fix is a riddle. */
export const REGENERATE_COMMAND = 'npm run catalogue-structure'

/** Compare what is served against what is committed. */
export const structureVerdict = (
  snapshot: CatalogueStructure,
  served: CatalogueStructure,
): StructureVerdict => {
  const committed = flatten(snapshot)
  const current = flatten(served)
  const paths = [...new Set([...committed.keys(), ...current.keys()])].sort()
  const differences: string[] = []

  for (const path of paths) {
    const was = committed.get(path)
    const now = current.get(path)

    if (was === now) continue
    if (was === undefined) differences.push(`+ ${path}: ${now}`)
    else if (now === undefined) differences.push(`- ${path}: was ${was}`)
    else differences.push(`~ ${path}: ${was} → ${now}`)
  }

  if (differences.length === 0) {
    return {
      unchanged: true,
      differences,
      message: `The catalogue's structure is unchanged: ${served.tools.length} tools, prose aside.`,
    }
  }

  const shown = differences.slice(0, DIFFERENCES_NAMED)
  const rest = differences.length - shown.length

  return {
    unchanged: false,
    differences,
    message: [
      `The catalogue's structure moved in ${differences.length} place${differences.length === 1 ? '' : 's'}, so this was not a prose change:`,
      ...shown,
      ...(rest > 0 ? [`… and ${rest} more.`] : []),
      `If the change is intended, regenerate the snapshot with \`${REGENERATE_COMMAND}\` and commit it — the structural diff then stands on its own.`,
    ].join('\n'),
  }
}
