import { readFileSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { describe, expect, it } from 'vitest'
import { connectedClient, registeredCitizen } from '../__fixtures__/mcp.js'
import type { PublishedTool } from './catalogue-size.js'
import {
  REGENERATE_COMMAND,
  structureOf,
  structureVerdict,
  type CatalogueStructureSnapshot,
} from './catalogue-structure.js'

/**
 * The guard that makes a prose rewrite reviewable (`#1227`).
 *
 * `#1115`, `#1117` and `#1229`–`#1231` rewrite descriptions across the whole
 * catalogue. Read as a diff, those commits are unreviewable for the one thing
 * that matters — whether anything *but* the prose moved. This holds the served
 * catalogue against a committed snapshot of its shape with every `description`
 * stripped, so a green run is the sentence *this was prose* and nothing else.
 *
 * It lives in the suite rather than in a script for the reason
 * `catalogue-budget.test.ts` gives: fixtures are kept out of `dist`, so a script
 * building its own server would be measuring something adjacent to what ships.
 * `scripts/write-catalogue-structure.mjs` runs this file with
 * {@link OUTPUT_PATH} set and commits what it writes.
 */

/** Where the regeneration script asks for the structure. Unset in an ordinary run, and then nothing is written. */
const OUTPUT_PATH = process.env['CATALOGUE_STRUCTURE_OUT']

/**
 * The snapshot, read as data rather than imported as a module — `resolveJsonModule`
 * would put a file a script rewrites into the api's `dist`.
 */
const SNAPSHOT_PATH = join(new URL('.', import.meta.url).pathname, 'catalogue-structure.json')
const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as CatalogueStructureSnapshot

/** The catalogue a connected citizen is handed — the tier every published description is paid for in. */
const servedCatalogue = async (): Promise<readonly PublishedTool[]> => {
  const { colony, apiKey } = await registeredCitizen()
  const citizen = await connectedClient(colony, `Bearer ${apiKey}`)

  try {
    return (await citizen.client.listTools()).tools as readonly PublishedTool[]
  } finally {
    await citizen.close()
  }
}

/** A catalogue small enough to reason about, standing in for the real one in the rejection cases. */
const twoTools: readonly PublishedTool[] = [
  {
    name: 'kolonie.example.write',
    description: 'Write something.',
    inputSchema: {
      type: 'object',
      properties: {
        slots: { type: 'integer', minimum: 1, maximum: 10_000, description: 'How many.' },
        kind: { type: 'string', enum: ['report', 'catalogue-entry', 'entry-walks'] },
        title: { type: 'string', maxLength: 120, description: 'One line.' },
      },
      required: ['slots'],
    },
  },
  {
    name: 'kolonie.example.read',
    description: 'Read it back.',
    inputSchema: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
  },
]

/** The same catalogue with one tool's schema altered, however the caller likes. */
const withSchema = (
  name: string,
  alter: (schema: Record<string, unknown>) => void,
): readonly PublishedTool[] =>
  twoTools.map((tool) => {
    if (tool.name !== name) return tool
    const schema = JSON.parse(JSON.stringify(tool.inputSchema)) as Record<string, unknown>
    alter(schema)
    return { ...tool, inputSchema: schema }
  })

describe('the committed snapshot', () => {
  it('carries the date and the command that produced it', () => {
    // AGENTS.md §7. The snapshot is regenerated by hand, so its provenance is
    // the only thing standing between a reader and a file somebody pasted.
    expect(snapshot.measuredAt).toMatch(/^\d{4}-\d{2}-\d{2}$/)
    expect(snapshot.command).toBe(REGENERATE_COMMAND)
    expect(snapshot.tools.length).toBeGreaterThan(0)
  })

  it('carries no prose of its own', () => {
    // The point of the file: it is the shape, and a sentence in it would make
    // the snapshot churn on every rewrite it exists to make legible. Nothing in
    // a stripped schema is long — a format, a slug, an enum value — so length is
    // the honest test, and 120 is far above the longest constraint the Colony
    // publishes.
    const strings: string[] = []
    const walk = (value: unknown): void => {
      if (typeof value === 'string') strings.push(value)
      else if (value !== null && typeof value === 'object') Object.values(value).forEach(walk)
    }
    walk(snapshot.tools)

    const prose = strings.filter((text) => text.length > 120)
    expect(prose, `the snapshot carries prose: ${prose[0] ?? ''}`).toHaveLength(0)
  })

  it('keeps a property that happens to be called `description`', () => {
    // A field named `description` is structure, and stripping by key name alone
    // would delete it — leaving the snapshot blind to the one change it exists
    // to catch. `kolonie.quests.write` has such a field.
    const quest = snapshot.tools.find((tool) => tool.name === 'kolonie.quests.write')
    const properties = (quest?.schema as { properties?: Record<string, unknown> } | undefined)
      ?.properties

    expect(properties?.['description']).toBeDefined()
  })
})

describe('a rewrite that only touched the prose', () => {
  it('passes with every description changed', () => {
    const reworded = twoTools.map((tool) => ({
      ...tool,
      description: 'Something else entirely.',
      inputSchema: JSON.parse(
        JSON.stringify(tool.inputSchema).replaceAll(
          /"description":"[^"]*"/g,
          '"description":"Reworded."',
        ),
      ) as unknown,
    }))

    const verdict = structureVerdict(structureOf(twoTools), structureOf(reworded))

    expect(verdict.unchanged, verdict.message).toBe(true)
    expect(verdict.differences).toHaveLength(0)
  })

  it('passes with a schema whose properties were declared in another order', () => {
    // Property order is an accident of how the Zod object was written. A check
    // that cried wolf on the first refactor would be turned off by the second.
    const reordered = withSchema('kolonie.example.write', (schema) => {
      const properties = schema['properties'] as Record<string, unknown>
      schema['properties'] = Object.fromEntries(Object.entries(properties).reverse())
    })

    expect(structureVerdict(structureOf(twoTools), structureOf(reordered)).unchanged).toBe(true)
  })
})

describe('a rewrite that moved the structure', () => {
  it('fails when a property is gone, and names it', () => {
    const withoutTitle = withSchema('kolonie.example.write', (schema) => {
      delete (schema['properties'] as Record<string, unknown>)['title']
    })

    const verdict = structureVerdict(structureOf(twoTools), structureOf(withoutTitle))

    expect(verdict.unchanged).toBe(false)
    expect(verdict.message).toContain('properties.title')
    expect(verdict.message).toContain('kolonie.example.write')
    // Naming the way back, because a check that hides its own fix is a riddle.
    expect(verdict.message).toContain(REGENERATE_COMMAND)
  })

  it('fails when a constraint was loosened, and gives both numbers', () => {
    const looser = withSchema('kolonie.example.write', (schema) => {
      const title = (schema['properties'] as Record<string, Record<string, unknown>>)['title']
      if (title !== undefined) title['maxLength'] = 400
    })

    const verdict = structureVerdict(structureOf(twoTools), structureOf(looser))

    expect(verdict.unchanged).toBe(false)
    expect(verdict.message).toContain('properties.title.maxLength: 120 → 400')
  })

  it('fails when an enum value was dropped', () => {
    const fewer = withSchema('kolonie.example.write', (schema) => {
      const kind = (schema['properties'] as Record<string, Record<string, unknown>>)['kind']
      if (kind !== undefined) kind['enum'] = ['report', 'catalogue-entry']
    })

    const verdict = structureVerdict(structureOf(twoTools), structureOf(fewer))

    expect(verdict.unchanged).toBe(false)
    expect(verdict.message).toContain('properties.kind.enum')
  })

  it('fails when a tool was added or removed', () => {
    const fewerTools = twoTools.slice(0, 1)
    const gone = structureVerdict(structureOf(twoTools), structureOf(fewerTools))
    const added = structureVerdict(structureOf(fewerTools), structureOf(twoTools))

    expect(gone.unchanged).toBe(false)
    expect(gone.message).toContain('kolonie.example.read')
    expect(added.unchanged).toBe(false)
    expect(added.message).toContain('kolonie.example.read')
  })
})

describe('the catalogue this build serves', () => {
  it('has the shape the snapshot records', async () => {
    const served = structureOf(await servedCatalogue())

    if (OUTPUT_PATH !== undefined && OUTPUT_PATH !== '') {
      // Written before the assertion on purpose: the regeneration script needs
      // the structure most in exactly the run where the check fails.
      await mkdir(dirname(OUTPUT_PATH), { recursive: true })
      await writeFile(OUTPUT_PATH, JSON.stringify(served, null, 2), 'utf8')
    }

    const verdict = structureVerdict(snapshot, served)

    expect(verdict.unchanged, verdict.message).toBe(true)
  })
})
